- name: This playbook will install, configure and deploy web page into nginx web server
  hosts: localhost 
  gather_facts: yes 
  vars:
    - provisioner_tool: Docker
    - conf_mgr_tool: Ansible
  tasks:
    - include: "install-nginx-{{ansible_distribution|lower}}.yml"

    - include: "configure-nginx-{{ansible_distribution|lower}}.yml"

    - include: common-nginx-tasks.yml
